### ISSUE TITLE
pszkotak's to-do list

### ISSUE THREAD

**Issue by pszkotak** [githubteacher/sep-22-developers#10]
## TODO
- [x] Create an issue
- [x] Create a branch
- [x] Create file locally and push it
- [x] Edit files GitHub.com and pull it
- [x] Create a Pull Request
- [x] Merge a Pull Request
- [x] Have a good time
