### ISSUE TITLE
X22 to-do list

### ISSUE THREAD

**Issue by X22** [githubteacher/sep-22-developers#11]
## To Do List
- [x] Create an issue
- [x] Create a branch
- [x] Create file locally and push it
- [ ] Edit files GitHub.com and pull it
- [ ] Create a Pull Request
- [ ] Merge a Pull Request

:+1:
