### ISSUE TITLE
humi todo

### ISSUE THREAD

**Issue by hubertmis** [githubteacher/sep-22-developers#15]
## To Do List
- [x] Create an issue  
- [ ] Create a Branch
- [ ] Create file locally and push it
- [ ] Create a Pull Request 
- [ ] Edit files GitHub.com and pull it
- [ ] Merge a Pull Request
- [ ] Have a good time?
- [ ] ?
  - [ ] ??
  - [ ] ???
