### ISSUE TITLE
sunjays to-do

### ISSUE THREAD

**Issue by sunjays** [githubteacher/sep-22-developers#16]
## To Do List
- [x] Create an issue
- [ ] Create a Branch
- [ ] Create file locally
- [x] Edit files GitHub.com on it
- [x] Merge a Pull Request
- [ ] Have a good time
