### ISSUE TITLE
ediamin's to-do list

### ISSUE THREAD

**Issue by ediamin** [githubteacher/sep-22-developers#18]
## TODO
- [x] Create an issue
- [x] Create a branch
- [x] Create file locally and push it
- [ ] Edit files GitHub.com and pull it
- [ ] Create a Pull Request
- [ ] Merge a Pull Request
- [ ] Have a good time

😸
