### ISSUE TITLE
eckstueck's to-do list

### ISSUE THREAD

**Issue by eckstueck** [githubteacher/sep-22-developers#19]
## To Do List
- [x] Create an issue
- [ ] Create a Branch
- [ ] Create file locally and push it
- [ ] Create a Pull Request
- [ ] Edit files GitHub.com and pull it
- [ ] Merge a Pull Request
- [ ] Have a good time?
