### ISSUE TITLE
rlubos' to-do list

### ISSUE THREAD

**Issue by rlubos** [githubteacher/sep-22-developers#22]
## To Do List
- [ ] Create an issue
- [ ] Create a branch
- [ ] Create file locally and push it
- [ ] Edit files GitHub.com and pull it
- [ ] Create a Pull Request
- [ ] Merge a Pull Request
- [x] Have a good time!
