### ISSUE TITLE
kkrebs to-do list

### ISSUE THREAD

**Issue by kkrebs** [githubteacher/sep-22-developers#23]
## To Do List
- [x] Create an issue  
- [x] Create a Branch
- [x] Create file locally and push it
- [x] Create a Pull Request 
- [x] Edit files GitHub.com and pull it
- [x] Merge a Pull Request
- [x] Have a good time?

:cat2:
