### ISSUE TITLE
eken378's to-do list

### ISSUE THREAD

**Issue by eken378** [githubteacher/sep-22-developers#25]
## TODO
- [x] Create an issue
- [x] Create a branch
- [ ] Create file locally and push it
- [ ] Edit files GitHub.com and pull it
- [ ] Create a Pull Request
- [ ] Merge a Pull Request
- [ ] Have a good time
