### ISSUE TITLE
master-smit to-do list

### ISSUE THREAD

**Issue by smitley** [githubteacher/sep-22-developers#3]
## To Do list
- [x] Create an issue
- [x] Create a Branch
- [ ] Create files GitHub.com and pull it
- [ ] Create an Pull Request :ship: 
- [ ] Merge a Pull request
- [ ] Have a great time
