### ISSUE TITLE
rafe's todo

### ISSUE THREAD

**Issue by rafesilver** [githubteacher/sep-22-developers#30]
- [x] Create an issue
- [x] Create a Branch
- [x] Create file locally and push it
- [x] Create a Pull Request
- [x] Edit files GitHub.com and pull it
- [x] Merge a Pull Request
- [x] Have a good time?
