### ISSUE TITLE
githubteacher's to-do list

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/sep-22-developers#4]
## To Do List
- [x] Create an issue  
- [x] Create a Branch
- [ ] Create file locally and push it
- [ ] Create a Pull Request 
- [ ] Edit files GitHub.com and pull it
- [ ] Merge a Pull Request
- [ ] Have a good time?

👍

**Comment by hectorsector** [comment]
☝️ no 😢

**Comment by manojhl** [comment]
what theme are you using with zsh?!!! It's so pretty ❤️

**Comment by hectorsector** [comment]
🎉

**Comment by hectorsector** [comment]
I'll jott it down to ask him @manojhl drop any more questions in Gitter chat
