### ISSUE TITLE
szymon to-do

### ISSUE THREAD

**Issue by ghost** [githubteacher/sep-22-developers#40]
## TO DO
- [x] Create an issue
- [x] Create a branch
- [x] Create file locally and push it
- [ ] Edit files GitHub.com and pull it
- [x] Create a Pull Request
- [ ] Merge a Pull Request
- [x] Have a good time
