### ISSUE TITLE
jhrabovsky's-TODO-list

### ISSUE THREAD

**Issue by jhrabovsky** [githubteacher/sep-22-developers#43]
My TODO list:
- [x] make this todo list. 
- [ ] create new branch
- [ ] do the rest
