### ISSUE TITLE
ahialy's to-do list

### ISSUE THREAD

**Issue by ahialy** [githubteacher/sep-22-developers#6]
## To Do List
- [x] Create an issue
- [x] Create a Branch
- [x] Create a file locally and push
- [x] Edit files on Github.com and pull it
- [x] Create a Pull request
- [x] Merge a Pull request
- [x] Have a good time ?

**Comment by ahialy** [comment]
Nice start
