### ISSUE TITLE
krlo to-do list

### ISSUE THREAD

**Issue by krlo** [githubteacher/sep-22-developers#7]
## To Do List
- [ ] Create an issue
- [x] Create a Branch
- [ ] Create files locally and push it
- [ ] Edit files GitHub.com and pull it
- [ ] Create a Pull Request
- [ ] Merge a Pull Request
- [ ] Have fun
