### ISSUE TITLE
dabeah's to-do list

### ISSUE THREAD

**Issue by dabeah** [githubteacher/sep-22-developers#8]
## To Do List
- [x] Create an issue
- [x] Create a branch
- [x] Create a file locally and push it
- [x] Edit files github.com and pull it
- [ ] Do other stuff

**Comment by lebdim45** [comment]
Just testing ...

**Comment by dabeah** [comment]
:+1:

**Comment by lebdim45** [comment]
:+1: haha
