### ISSUE TITLE
dcprevere's to-do list

### ISSUE THREAD

**Issue by DCPRevere** [githubteacher/sep-22-developers#9]
## To Do List
- [x] Create an issue
- [ ] Create a branch
- [ ] Create file locally and commit it
- [ ] Edit files in GitHub.com and pull it
- [ ] Create a pull request
- [ ] Merge a pull request
- [ ] Have a good time
