### ISSUE TITLE
A-team todo list

### ISSUE THREAD

**Issue by davidknilsson** [githubteacher/sep-22-developers#90]

**Comment by davidknilsson** [comment]
- [x] take the courser
 - [x] open an Git-hub project
 - [ ] do a killer app 
 - [ ] get enormous rich  
 - [ ] live my life in the sun 

:open_mouth:

**Comment by davidknilsson** [comment]
:+1: :ok_hand:

**Comment by blessyperumal** [comment]
@davidknilsson can you assign issues?

**Comment by p-3** [comment]
kaka
