### ISSUE TITLE
blessy's to-do list

### ISSUE THREAD

**Issue by blessyperumal** [githubteacher/sep-22-developers#91]
## To Do List

- [x] Create an issue
- [ ] Create a branch
- [ ] Edit files locally and push it
- [ ] Create a Pull req
- [ ] Edit files GitHub.com and pull it
- [ ] Merge a Pull req
- [ ] Merry Christmas? 

:christmas_tree: :santa: :+1:

**Comment by davidknilsson** [comment]
:+1: :+1:
